name: Release Obsidian plugin

permissions: write-all

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }} # tag="${GITHUB_REF#refs/tags/}"
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          message=$(git tag -l --format='%(contents)' $tag)

          gh release create "$tag" \
            --title="$tag" \
            --notes="${message}" \
            --verify-tag \
            main.js manifest.json styles.css
